# docker-compose.yml

version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: ridehive_redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ridehive_app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: sqlite:////app/data/ridehive.db  # ✅ new path
    volumes:
      - .:/app
      - db_data:/app/data                            # ✅ mount directory not file
    command: uvicorn gateway.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ridehive_worker
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: sqlite:////app/data/ridehive.db  # ✅ same path
    volumes:
      - .:/app
      - db_data:/app/data                            # ✅ same directory
    command: python worker.py
    restart: unless-stopped


volumes:
  redis_data:
  db_data: